### ISSUE TITLE
Need to support the new query and update requests for license agreements

### ISSUE THREAD

**Issue by Nilzor** [schibsted/sdk-android#18]
Specifically 

 - [ ] GET request: http://techdocs.spid.no/endpoints/GET/user/%7BuserId%7D/agreements/
 - [ ] POST request: http://techdocs.spid.no/endpoints/POST/user/%7BuserId%7D/agreements/accept/

I'm thinking three or four new functions in `SPiDClient.java`: 

 - `getAgreements(userId)` - Return list of accepted license agreements as strongly typed objects
 - `hasAcceptedAgreement(userId)` -use current configured clilent/platform as input to endpoint
 - `hasAcceptedAgreement(userId, client, platform)` -query for specific client/platform (other than current)
 - `void acceptAgreement(userId)` -accept for currenct client/platform

All methods will have async callbacks in the same pattern as `getCurrentUser` for instance (`SPiDRequestListener`). You probably need to expand on the interfaces or create new ones.

**Comment by joawan** [comment]
getAgreements(userId), fine
acceptAgreement(userId), fine

hasAcceptedAgreement will use getAgreements?
Can you provide more info about the use of those?

**Comment by Nilzor** [comment]
Yea both the `hasAcceptedAgreement` I thought would be convenience method utilizing `getAgreements` . 

I'm unsure exactly what the `platform` parameter . Do you know?

**Comment by grzegorzkurtyka** [comment]
Well, this is SPiD SDK for android, by that I mean this is intended for single service application (ie. android app for web newspaper edition). In that case I don't see use for things like: "Return list of accepted license agreements" IMO for application developers using this SDK most convinient methods would include (in context of given user and client) `hasAcceptedAgreement`, `acceptAgreement`, `getAgreement` for fetching and presenting agreement content to user.

**Comment by joawan** [comment]
@Nilzor client and platform are not parameters. They are only part of the response.

* client (bool), has user accepted client agreement
* platform (bool), has user accepted SPiD agreement

So having two separate methods for that might be unwise. We especially do not want 2 requests to agreement endpoint.

I do agree with @grzegorzkurtyka about the functions.
`hasAcceptedAgreement`, should call "GET user/id/agreements". It should return which agreements user needs to accept. So we should name that better. Like `getAgreementsRequiringAcceptance` or something smarter.

`acceptAgreement` should call the "POST user/id/agreements/accept"

`getAgreement` should call the "GET /terms" endpoint, to get the actual text. That should already be implemented in the SDK.

**Comment by Nilzor** [comment]
Yea sounds like we're getting closer to a proper spec now.

>getAgreement should call the "GET /terms" endpoint, to get the actual text. That should already be implemented in the SDK.

Myea.. not really :) It's only provided as an example in the Hybrid app project. At VG we basically copy pasted this code. Not an ideal solution:

https://github.com/schibsted/sdk-android/blob/46f9fa16f1e27f800e3da2d92fbfedc015bae1ed/SPiDHybridApp/src/main/java/com/spid/android/example/hybridapp/TermsDialog.java#L57

**Comment by joawan** [comment]
Ouch, did not know that. That should be fixed.

The flow is that user will login, (or signup via Facebook), and then app need to check if agreements are accepted. If not, a webview/native view should be opened with 2 checkboxes.
1 checkbox for SPiD and Client terms, 1 checkbox for SPiD Privacy policy and Client Privacy policy.

These documents can be links, and can be opened in webview. I wonder if we even need the /terms endpoint. Is there a need to show the terms in a native view instead of webview? In the rare cases a user taps the links?

We need to add an API to get those links though, and it's a todo.
* Link to SPiD agreement
* Link to Client agreement
* Link to SPiD Privacy policy
* Link to Client Privacy policy

**Comment by Nilzor** [comment]
> Is there a need to show the terms in a native view instead of webview?

No. Not that I can think of,

**Comment by Nilzor** [comment]
As for naming, what about `getPendingAgreements` instead of `getAgreementsRequiringAcceptance`?

**Comment by joawan** [comment]
Sounds better!

**Comment by Nilzor** [comment]
FYI. Przemysław Zieliński,  github user [ziem](https://github.com/ziem) and a developer for STP will create a pull request for this feature soon.

Fetching the terms text/url will not be a part of the scope - I suggest we extract that to a separate issue, as there isn't even a REST endpoint for it yet, afaik
