### ISSUE TITLE
Building binary is not working

### ISSUE THREAD

**Issue by damianpetla** [schibsted/sdk-android#6]
I am trying to build jar binary following instruction from the github start page. Only javadoc and sources jars are built.

**Comment by damianpetla** [comment]
I was able to workaround this problem. First I used Gradle task `uploadArtifacts`. Then I copied the `SPiD-Android-1.3.2.aar` from my local repo to the project `libs` folder. Next I have updated my gradle build files.

Main build.gradle
```
allprojects {
    repositories {
        ...
        flatDir {
            dirs 'libs'
        }
    }
}
```

Module build.gradle
`compile(name:'SPiD-Android-1.3.2', ext:'aar')`

**Comment by oskarh** [comment]
Hi Damian,

Sorry for the late response.

I added the aar file to Github so others won't have to build it themselves.

Let us know if you have any other suggestions or improvements!
