### ISSUE TITLE
Provide library via repository

### ISSUE THREAD

**Issue by outlying** [schibsted/sdk-android#7]
Could you provide whole library via repository ? Like MavenCentral since source code is already open or use GitHub http://kwebble.com/blog/2014/02/19/use-github-to-host-your-own-maven-repo ?

**Comment by oskarh** [comment]
Hi,

We will add it to a maven repository com.schibsted, but need to add proof of domain ownership before we can to that so we can't do that right now. I added the aar file to Github so you can use that library for now until we fix that.
